image: node:latest
before_script:
  - python -V
  - gem install dpl

stages:
    - develop
    - production

develop:
    stage: develop
    image: ruby:latest
    script:
    - dpl --provider=heroku --app=$HEROKU_APP_DEVELOP --api-key=$HEROKU_API_KEY 
    only:
        - develop

production:
    stage: production
    image: ruby:latest
    script:
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY 
    only:
        - master